Revert "UBUNTU: [Packaging] linux-tools: switch to common generic version helper"
This reverts commit 1ce943440716b85702d59ce5f690f0cc2f51f05b.

diff --git a/debian/tools/perf b/debian/tools/perf
--- a/debian/tools/perf
+++ b/debian/tools/perf
@@ -5,12 +5,12 @@ full_version=`uname -r`
 flavour_abi=${full_version#*-}
 flavour=${flavour_abi#*-}
 version=${full_version%-$flavour}
-this="$0_$version"
+perf="perf_$version"
 
-if [ ! -f "$this" ]; then
-    echo "$this not found" >&2
+if ! which "$perf" > /dev/null; then
+    echo "$perf not found" >&2
     echo "You may need to install linux-tools-$version" >&2
     exit 2
 fi
 
-exec "$this" "$@"
+exec "$perf" "$@"
diff --git a/debian/tools/x86_energy_perf_policy b/debian/tools/x86_energy_perf_policy
--- a/debian/tools/x86_energy_perf_policy
+++ b/debian/tools/x86_energy_perf_policy
@@ -5,12 +5,12 @@ full_version=`uname -r`
 flavour_abi=${full_version#*-}
 flavour=${flavour_abi#*-}
 version=${full_version%-$flavour}
-this="$0_$version"
+x86_energy_perf_policy="x86_energy_perf_policy_$version"
 
-if [ ! -f "$this" ]; then
-    echo "$this not found" >&2
+if ! which "$x86_energy_perf_policy" > /dev/null; then
+    echo "$x86_energy_perf_policy not found" >&2
     echo "You may need to install linux-tools-$version" >&2
     exit 2
 fi
 
-exec "$this" "$@"
+exec "$x86_energy_perf_policy" "$@"
